theme: minima
title: Aidan G Aerospace Portfolio
description: Aerospace engineering modeling | Simulation | Systems Analysis | Aerodynamic Design | Embedded Software | Electronic Design | CAD modeling